# Generated by Django 4.2 on 2025-07-30 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_identifier",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="记录唯一标识"
                    ),
                ),
                (
                    "observation_start_time",
                    models.DateTimeField(verbose_name="观察开始时间"),
                ),
                (
                    "observation_end_time",
                    models.DateTimeField(verbose_name="观察结束时间"),
                ),
                (
                    "observation_address",
                    models.CharField(max_length=255, verbose_name="观察地址"),
                ),
                ("bird_count", models.IntegerField(verbose_name="鸟类总数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bird_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="记录用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "鸟类观察记录",
                "verbose_name_plural": "鸟类观察记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecordDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_counts",
                    models.CharField(max_length=255, verbose_name="基本统计"),
                ),
                ("longitude", models.FloatField(verbose_name="经度")),
                ("latitude", models.FloatField(verbose_name="纬度")),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="bird_api.record",
                        verbose_name="所属记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "记录详情",
                "verbose_name_plural": "记录详情",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="评论内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="bird_api.record",
                        verbose_name="所属记录",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评论用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpeciesCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count_id", models.IntegerField(verbose_name="统计ID")),
                ("china_name", models.CharField(max_length=100, verbose_name="中文名")),
                ("order_name", models.CharField(max_length=100, verbose_name="目")),
                ("family_name", models.CharField(max_length=100, verbose_name="科")),
                ("count", models.IntegerField(verbose_name="数量")),
                (
                    "record_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_counts",
                        to="bird_api.recorddetail",
                        verbose_name="所属记录详情",
                    ),
                ),
            ],
            options={
                "verbose_name": "物种统计",
                "verbose_name_plural": "物种统计",
                "ordering": ["count_id"],
                "unique_together": {("record_detail", "count_id")},
            },
        ),
    ]
