# Generated by Django 4.2 on 2025-04-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aqirecord",
            name="co",
            field=models.CharField(blank=True, null=True, verbose_name="CO(mg/m³)"),
        ),
        migrations.AlterField(
            model_name="aqirecord",
            name="no2",
            field=models.CharField(blank=True, null=True, verbose_name="NO2(μg/m³)"),
        ),
        migrations.AlterField(
            model_name="aqirecord",
            name="o3",
            field=models.CharField(blank=True, null=True, verbose_name="O3(μg/m³)"),
        ),
        migrations.AlterField(
            model_name="aqirecord",
            name="pm10",
            field=models.CharField(blank=True, null=True, verbose_name="PM10(μg/m³)"),
        ),
        migrations.AlterField(
            model_name="aqirecord",
            name="pm25",
            field=models.CharField(blank=True, null=True, verbose_name="PM2.5(μg/m³)"),
        ),
        migrations.AlterField(
            model_name="aqirecord",
            name="so2",
            field=models.CharField(blank=True, null=True, verbose_name="SO2(μg/m³)"),
        ),
    ]
